AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Exclude:
  - "spec/**/*"

Style/FileName:
  Exclude:
  - "lib/middleman-dato.rb"
